=== cedricwalter/joomla-xsd/package.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <xs:include schemaLocation="./common.xsd"/>
  
  <xs:element name="extension">
    <xs:complexType>
      <xs:all>
        <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="packagename" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="version" type="versionType" minOccurs="1" maxOccurs="1"/>
        <xs:element name="url" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
        <xs:element name="packager" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="packagerurl" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
        <xs:element name="description" type="xs:normalizedString"/>
        <xs:element name="scriptfile" type="validScript" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="updateservers" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="files" minOccurs="0" maxOccurs="1"/>
        <xs:element name="update" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
      </xs:all>

      <xs:attribute name="method" default="upgrade" type="methodType"/>
      <xs:attribute name="type" use="required" type="typeType"/>
      <xs:attribute name="version" use="required" type="cmsversion"/>
    </xs:complexType>
  </xs:element>


  <xs:element name="files">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="file"/>
      </xs:sequence>
      <xs:attribute name="folder" use="optional" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="file">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="validSubPackageType">
          <xs:attribute name="client" type="clientType"/>
          <xs:attribute name="group" type="xs:string"/>
          <xs:attribute name="id" use="required" type="xs:NCName"/>
          <xs:attribute name="type" use="required" type="typeType"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:simpleType name="validSubPackageType">
    <xs:annotation>
      <xs:documentation xml:lang="en">Validate filepath</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="[.A-Za-z0-9_-]*.zip"/>
    </xs:restriction>
  </xs:simpleType>
  
  
</xs:schema>

=== cedricwalter/joomla-xsd/package.xml
<?xml version="1.0" encoding="UTF-8" ?>
<extension type="package" version="3.0" xsi:noNamespaceSchemaLocation="./package.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Everything Demonstration</name>
	<packagename>everything</packagename>
	<version>3.0.0</version>
	<url>http://www.joomla.org</url>
	<packager>Sam Moffatt</packager>
	<packagerurl>http://www.sammoffatt.com.au</packagerurl>
	<description>Joomla! Installer Sample and Test Package.</description>
	<update>http://update.joomla.org/update/packages/everything</update>
	
	<scriptfile>file.script.php</scriptfile> 
	
	<updateservers>
		<server type="extension" priority="1" name="Extension Update Site">http://jsitepoint.com/update/package/everything/extension.xml</server>
		<server type="collection" priority="2" name="Collection Update Site">http://jsitepoint.com/update/update.xml</server>
	</updateservers>
	
	<files folder="packages">
		<file type="library" 	id="lib_alpha" >lib_alpha.zip</file>
		<file type="component" 	id="com_alpha" >com_alpha.zip</file>
		<file type="module" 	id="mod_alpha" 	client="site">mod_alpha.zip</file>
		<file type="module"		id="mod_adminalpha" 	client="administrator">mod_alpha_admin.zip</file>
		<file type="plugin"		id="alpha"		group="system">plg_system_alpha.zip</file>
		<file type="template"	id="simple_template"	client="site">tpl_simple.zip</file>
		<file type="language"	id="xx-XX" client="site">lng_xx-XX.zip</file>
		<file type="language" 	id="xx-XX" client="administrator">lng_xx-XX_admin.zip</file>
	</files>
</extension>
